"""
Branded PDF Library for research.md

Parameterizable brand system for research briefs, reports, and exports.
Learned from greenmark_pdf.py patterns (BrandHeader, AccentBox, StatCard)
but independently maintained with configurable brand colors.

Usage:
    from pdf_brand import Brand, BrandHeader, AccentBox, StatCard, tbl, hr, build_doc
    brand = Brand.from_preset("connection-forge")
    # or: brand = Brand(primary="#193B2D", name="My Brand")
"""

from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white, Color
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, Image,
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus.flowables import Flowable


# ── Page Layout ──────────────────────────────────────────────────────
W, H = letter
MARGIN = 0.6 * inch
USABLE = W - 2 * MARGIN


# ── Brand System ─────────────────────────────────────────────────────

class Brand:
    """Parameterizable brand configuration for PDF generation."""

    PRESETS = {
        "connection-forge": {
            "primary": "#193B2D",
            "primary_light": "#E8F0EC",
            "accent": "#2D6B4A",
            "muted": "#6B7B73",
            "name": "Connection Forge",
            "footer": "Connection Forge — Vendor Integration Contracts by Eidos",
        },
        "aic": {
            "primary": "#1B365D",
            "primary_light": "#E3F2FD",
            "accent": "#2E86C1",
            "muted": "#6B7B8D",
            "name": "AIC Holdings",
            "footer": "AIC Holdings — Technology Leadership",
        },
        "research": {
            "primary": "#37474F",
            "primary_light": "#ECEFF1",
            "accent": "#546E7A",
            "muted": "#78909C",
            "name": "research.md",
            "footer": "Generated by research.md — Structured Research for AI-Augmented Decision Making",
        },
    }

    def __init__(self, primary="#37474F", primary_light=None, accent=None,
                 muted=None, name="research.md", footer=None, logo_path=None):
        self.primary = HexColor(primary)
        self.primary_light = HexColor(primary_light or self._lighten(primary))
        self.accent = HexColor(accent or primary)
        self.muted = HexColor(muted or "#78909C")
        self.dark = HexColor("#1A1A1A")
        self.white = white
        self.grid = HexColor("#D0D0D0")
        self.name = name
        self.footer_text = footer or name
        self.logo_path = logo_path

    @staticmethod
    def _lighten(hex_color):
        """Create a light version of a hex color for backgrounds."""
        h = hex_color.lstrip('#')
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        # Blend toward white at 85%
        r = int(r + (255 - r) * 0.85)
        g = int(g + (255 - g) * 0.85)
        b = int(b + (255 - b) * 0.85)
        return f"#{r:02x}{g:02x}{b:02x}"

    @classmethod
    def from_preset(cls, name, **overrides):
        if name not in cls.PRESETS:
            name = "research"
        p = cls.PRESETS[name].copy()
        p.update(overrides)
        return cls(
            primary=p.get("primary", "#37474F"),
            primary_light=p.get("primary_light"),
            accent=p.get("accent"),
            muted=p.get("muted"),
            name=p.get("name", name),
            footer=p.get("footer"),
            logo_path=p.get("logo_path"),
        )

    # ── Styles ───────────────────────────────────────────────────────

    def styles(self):
        """Build a dict of branded ParagraphStyles."""
        return {
            "body": ParagraphStyle("body", fontName="Helvetica", fontSize=9,
                                   leading=13, textColor=self.dark),
            "body_bold": ParagraphStyle("body_bold", fontName="Helvetica-Bold",
                                        fontSize=9, leading=12, textColor=self.dark),
            "h1": ParagraphStyle("h1", fontName="Helvetica-Bold", fontSize=14,
                                 leading=18, textColor=self.primary, spaceAfter=4),
            "h2": ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=11,
                                 leading=14, textColor=self.accent,
                                 spaceBefore=14, spaceAfter=4),
            "h3": ParagraphStyle("h3", fontName="Helvetica-Bold", fontSize=9.5,
                                 leading=12, textColor=self.primary,
                                 spaceBefore=6, spaceAfter=2),
            "meta": ParagraphStyle("meta", fontName="Helvetica", fontSize=8,
                                   leading=10, textColor=self.muted),
            "cell": ParagraphStyle("cell", fontName="Helvetica", fontSize=8,
                                   leading=10, textColor=self.dark),
            "cell_bold": ParagraphStyle("cell_bold", fontName="Helvetica-Bold",
                                        fontSize=8, leading=10, textColor=self.dark),
            "cell_header": ParagraphStyle("cell_header", fontName="Helvetica-Bold",
                                          fontSize=8, leading=10, textColor=white),
            "cell_center": ParagraphStyle("cell_center", fontName="Helvetica",
                                          fontSize=8, leading=10,
                                          textColor=self.dark, alignment=TA_CENTER),
            "mono": ParagraphStyle("mono", fontName="Courier", fontSize=7.5,
                                   leading=10, textColor=self.accent),
            "bullet": ParagraphStyle("bullet", fontName="Helvetica", fontSize=9,
                                     leading=12, textColor=self.dark,
                                     leftIndent=16, bulletIndent=4, spaceAfter=6),
        }


# ── Flowables ────────────────────────────────────────────────────────

class BrandHeader(Flowable):
    """Dark rounded rect with logo/brand name, title, and subtitle."""

    def __init__(self, brand, title, subtitle, width=None):
        super().__init__()
        self.brand = brand
        self.width = width or USABLE
        self.height = 0.95 * inch
        self.title = title
        self.subtitle = subtitle

    def draw(self):
        c = self.canv
        c.setFillColor(self.brand.primary)
        c.roundRect(0, 0, self.width, self.height, 6, fill=1, stroke=0)

        if self.brand.logo_path and Path(self.brand.logo_path).exists():
            try:
                c.drawImage(self.brand.logo_path, 12, self.height - 32,
                            width=1.35 * inch, height=0.28 * inch,
                            preserveAspectRatio=True, mask="auto")
            except Exception:
                c.setFont("Helvetica-Bold", 9)
                c.setFillColor(HexColor("#A8C4B4"))
                c.drawString(12, self.height - 24, self.brand.name)
        else:
            c.setFont("Helvetica-Bold", 9)
            c.setFillColor(HexColor("#A8C4B4"))
            c.drawString(12, self.height - 24, self.brand.name)

        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(12, 14, self.title)
        c.setFont("Helvetica", 9)
        c.setFillColor(HexColor("#A8C4B4"))
        c.drawRightString(self.width - 12, 14, self.subtitle)


class AccentBox(Flowable):
    """Rounded callout box with left accent stripe. Auto word-wraps."""

    def __init__(self, brand, text, width=None, bg=None, border=None,
                 text_color=None, bold=True, size=9):
        super().__init__()
        self.width = width or USABLE
        _bg = bg or brand.primary_light
        _border = border or brand.accent
        _tc = text_color or brand.primary
        sty = ParagraphStyle("ab", fontName="Helvetica-Bold" if bold else "Helvetica",
                             fontSize=size, leading=size + 3, textColor=_tc)
        self._para = Paragraph(text, sty)
        pw = self.width - 20
        _, self._ph = self._para.wrap(pw, 999)
        self.height = self._ph + 14
        self.bg = _bg
        self.border = _border

    def draw(self):
        c = self.canv
        c.setFillColor(self.bg)
        c.roundRect(0, 0, self.width, self.height, 4, fill=1, stroke=0)
        c.setFillColor(self.border)
        c.rect(0, 0, 4, self.height, fill=1, stroke=0)
        self._para.drawOn(c, 14, (self.height - self._ph) / 2)


class StatCard(Flowable):
    """Row of stat cards — light boxes with accent bar on top."""

    def __init__(self, brand, stats, width=None):
        super().__init__()
        self.brand = brand
        self.width = width or USABLE
        self.height = 0.7 * inch
        self.stats = stats  # list of (value, label) tuples

    def draw(self):
        c = self.canv
        n = len(self.stats)
        gap = 6
        cw = (self.width - gap * (n - 1)) / n
        for i, (value, label) in enumerate(self.stats):
            x = i * (cw + gap)
            c.setFillColor(self.brand.primary_light)
            c.roundRect(x, 0, cw, self.height, 4, fill=1, stroke=0)
            c.setFillColor(self.brand.accent)
            c.rect(x, self.height - 4, cw, 4, fill=1, stroke=0)
            c.setFont("Helvetica-Bold", 20)
            c.setFillColor(self.brand.primary)
            c.drawCentredString(x + cw / 2, 18, str(value))
            c.setFont("Helvetica", 7)
            c.setFillColor(self.brand.muted)
            c.drawCentredString(x + cw / 2, 6, label)


class LayerCard(Flowable):
    """A single layer in an architecture diagram — rounded box with accent."""

    def __init__(self, brand, number, name, pattern, description, read_time,
                 width=None, is_even=True):
        super().__init__()
        self.brand = brand
        self.width = width or USABLE
        self.number = str(number)
        self.name = name
        self.pattern = pattern
        self.description = description
        self.read_time = read_time
        self.is_even = is_even

        # Pre-compute text heights
        sty_desc = ParagraphStyle("ld", fontName="Helvetica", fontSize=8,
                                   leading=11, textColor=brand.dark)
        self._desc_para = Paragraph(description, sty_desc) if description else None
        inner_w = self.width - 0.5 * inch - 1.0 * inch - 24
        self._desc_h = 0
        if self._desc_para:
            _, self._desc_h = self._desc_para.wrap(inner_w, 999)
        self.height = max(0.5 * inch, self._desc_h + 36)

    def draw(self):
        c = self.canv
        bg = self.brand.primary_light if self.is_even else white
        c.setFillColor(bg)
        c.roundRect(0, 0, self.width, self.height, 4, fill=1, stroke=0)

        # Left accent bar
        c.setFillColor(self.brand.accent)
        c.roundRect(0, 0, 5, self.height, 2, fill=1, stroke=0)

        # Number
        c.setFont("Helvetica-Bold", 18)
        c.setFillColor(self.brand.primary)
        c.drawCentredString(0.3 * inch, self.height / 2 - 6, self.number)

        # Name
        x = 0.55 * inch
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(self.brand.primary)
        c.drawString(x, self.height - 14, self.name)

        # Pattern (italic)
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(self.brand.muted)
        c.drawString(x, self.height - 25, self.pattern)

        # Description
        if self._desc_para:
            self._desc_para.drawOn(c, x, 4)

        # Read time (right aligned)
        c.setFont("Helvetica", 8)
        c.setFillColor(self.brand.muted)
        c.drawRightString(self.width - 8, self.height / 2 - 4, self.read_time)


# ── Table Builder ────────────────────────────────────────────────────

def tbl(brand, header, rows, widths):
    """Standard branded table — dark header, alternating rows, rounded feel."""
    data = [header] + rows
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), brand.primary),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("LEADING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, brand.grid),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), brand.primary_light))
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle(style))
    return t


# ── Helpers ──────────────────────────────────────────────────────────

def hr(brand=None):
    """Thin horizontal rule."""
    color = brand.grid if brand else HexColor("#D0D0D0")
    return HRFlowable(width="100%", thickness=0.5, color=color,
                      spaceBefore=6, spaceAfter=8)


def make_footer(brand):
    """Return a footer function for branded pages."""
    def footer_func(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(brand.muted)
        canvas.drawString(MARGIN, 0.35 * inch,
                          f"{brand.footer_text}  |  {datetime.now().strftime('%Y-%m-%d')}")
        canvas.drawRightString(W - MARGIN, 0.35 * inch, f"Page {doc.page}")
        canvas.restoreState()
    return footer_func


def build_doc(output_path, brand, doc_title, build_fn):
    """Create a branded PDF. build_fn(story) adds content to the story list."""
    doc = SimpleDocTemplate(str(output_path), pagesize=letter,
                            leftMargin=MARGIN, rightMargin=MARGIN,
                            topMargin=MARGIN, bottomMargin=0.6 * inch)
    story = []
    build_fn(story)
    footer = make_footer(brand)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    print(f"PDF saved: {output_path}")
