#!/usr/bin/env python3
"""
render-brief.py — Convert a research BRIEF.md to a branded PDF.

Standalone renderer for research.md. No shared code with other pipelines.
Learns from render_adr.py patterns but is independently maintained.

Usage:
    python3 render-brief.py BRIEF.md
    python3 render-brief.py BRIEF.md --brand connection-forge
    python3 render-brief.py BRIEF.md --brand-color "#193B2D" --brand-name "AIC Holdings"
    python3 render-brief.py BRIEF.md --logo logo.png -o output.pdf

Brand presets:
    --brand connection-forge   → AIC green, "Connection Forge" footer
    --brand aic                → AIC blue, "AIC Holdings" footer
    --brand research           → Neutral gray, "research.md" footer
"""

import argparse
import os
import re
import sys

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
        HRFlowable, KeepTogether, CondPageBreak
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER
except ImportError:
    print("pip install reportlab", file=sys.stderr)
    sys.exit(1)


# ── Brand Presets ─────────────────────────────────────────────────────────────

BRANDS = {
    "connection-forge": {
        "primary": "#193B2D",
        "primary_light": "#E8F5E9",
        "primary_med": "#A5D6A7",
        "name": "Connection Forge",
        "footer": "Connection Forge — Vendor Integration Contracts by AIC Holdings",
    },
    "aic": {
        "primary": "#1B365D",
        "primary_light": "#E3F2FD",
        "primary_med": "#90CAF9",
        "name": "AIC Holdings",
        "footer": "AIC Holdings — Technology Leadership",
    },
    "research": {
        "primary": "#37474F",
        "primary_light": "#ECEFF1",
        "primary_med": "#B0BEC5",
        "name": "research.md",
        "footer": "Generated by research.md — Structured Research for AI-Augmented Decision Making",
    },
}

PAGE_MARGIN = 0.75 * inch
# Minimum space before a H2 heading to avoid orphaned headers at page bottom
MIN_H2_SPACE = 2.0 * inch

# Box-drawing characters used in ASCII architecture diagrams
BOX_CHARS = set('┌┐└┘├┤┬┴─│╭╮╰╯║═╔╗╚╝╠╣╦╩')


def get_brand(args):
    """Resolve brand settings from args."""
    if args.brand and args.brand in BRANDS:
        b = BRANDS[args.brand]
    else:
        b = BRANDS["research"]

    # Allow overrides
    if args.brand_color:
        b["primary"] = args.brand_color
    if args.brand_name:
        b["name"] = args.brand_name
        b["footer"] = args.brand_name

    return {
        "primary": colors.HexColor(b["primary"]),
        "primary_light": colors.HexColor(b["primary_light"]),
        "primary_med": colors.HexColor(b["primary_med"]),
        "name": b["name"],
        "footer": b["footer"],
        "text": colors.HexColor("#1a1a1a"),
        "text_secondary": colors.HexColor("#4a4a4a"),
        "border": colors.HexColor(b.get("primary_med", "#B0BEC5")),
    }


def build_styles(brand):
    """Create branded paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        'Brief_Title', parent=styles['Title'],
        fontSize=22, leading=28, textColor=brand["primary"],
        spaceAfter=4, fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        'Brief_Subtitle', parent=styles['Normal'],
        fontSize=12, leading=16, textColor=brand["text_secondary"],
        spaceAfter=12, fontName='Helvetica-Oblique'
    ))
    styles.add(ParagraphStyle(
        'Brief_Meta', parent=styles['Normal'],
        fontSize=9, leading=13, textColor=brand["text_secondary"],
        spaceAfter=2, fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        'Brief_H2', parent=styles['Heading2'],
        fontSize=14, leading=18, textColor=brand["primary"],
        spaceBefore=4, spaceAfter=6, fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        'Brief_H3', parent=styles['Heading3'],
        fontSize=11, leading=15, textColor=brand["primary"],
        spaceBefore=10, spaceAfter=4, fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        'Brief_Body', parent=styles['Normal'],
        fontSize=10, leading=14, textColor=brand["text"],
        spaceAfter=6, fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        'Brief_Verdict', parent=styles['Normal'],
        fontSize=11, leading=16, textColor=brand["text"],
        spaceAfter=4, fontName='Helvetica-Bold',
        backColor=brand["primary_light"],
        borderColor=brand["primary"], borderWidth=1, borderPadding=8,
    ))
    styles.add(ParagraphStyle(
        'Brief_Bullet', parent=styles['Normal'],
        fontSize=10, leading=14, textColor=brand["text"],
        spaceAfter=8, fontName='Helvetica',
        leftIndent=18, bulletIndent=6
    ))
    styles.add(ParagraphStyle(
        'Brief_Code', parent=styles['Code'],
        fontSize=7, leading=10, textColor=colors.HexColor('#333333'),
        backColor=colors.HexColor('#f5f5f5'),
        borderColor=brand["border"], borderWidth=0.5, borderPadding=6,
        fontName='Courier', spaceAfter=8
    ))
    styles.add(ParagraphStyle(
        'Brief_TableCell', parent=styles['Normal'],
        fontSize=9, leading=12, textColor=brand["text"],
        fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        'Brief_TableHeader', parent=styles['Normal'],
        fontSize=9, leading=12, textColor=colors.white,
        fontName='Helvetica-Bold'
    ))
    # Layer card styles for architecture diagrams
    styles.add(ParagraphStyle(
        'Brief_LayerNumber', parent=styles['Normal'],
        fontSize=18, leading=22, textColor=brand["primary"],
        fontName='Helvetica-Bold', alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        'Brief_LayerName', parent=styles['Normal'],
        fontSize=10, leading=13, textColor=brand["primary"],
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        'Brief_LayerPattern', parent=styles['Normal'],
        fontSize=8, leading=11, textColor=brand["text_secondary"],
        fontName='Helvetica-Oblique',
    ))
    styles.add(ParagraphStyle(
        'Brief_LayerDesc', parent=styles['Normal'],
        fontSize=9, leading=12, textColor=brand["text"],
        fontName='Helvetica',
    ))
    styles.add(ParagraphStyle(
        'Brief_LayerTime', parent=styles['Normal'],
        fontSize=8, leading=10, textColor=brand["text_secondary"],
        fontName='Helvetica', alignment=TA_CENTER,
    ))
    return styles


def inline_markup(text, brand_hex="#37474F"):
    """Convert inline markdown to reportlab XML markup."""
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<b><i>\1</i></b>', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    text = re.sub(r'`([^`]+)`', rf'<font face="Courier" size="8" color="{brand_hex}">\1</font>', text)
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'<u>\1</u>', text)
    # Escape XML then restore tags
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    for tag in ['b', 'i', 'u', 'font']:
        text = text.replace(f'&lt;{tag}&gt;', f'<{tag}>')
        text = text.replace(f'&lt;{tag} ', f'<{tag} ')
        text = text.replace(f'&lt;/{tag}&gt;', f'</{tag}>')
    text = re.sub(r'<font([^&]*?)&gt;', r'<font\1>', text)
    return text


def _has_box_drawing(text):
    """Check whether text contains box-drawing characters."""
    return any(ch in BOX_CHARS for ch in text)


def _parse_layer_diagram(code_text):
    """Parse an ASCII box-drawing layer diagram into structured layer data.

    Looks for patterns like:
        LAYER N: Title
        Pattern: ...
        description lines
        Read time: ...

    Returns a list of dicts or None if parsing fails.
    """
    layers = []
    current = None

    for line in code_text.split('\n'):
        # Strip box-drawing chrome
        stripped = line.strip()
        for ch in BOX_CHARS:
            stripped = stripped.replace(ch, '')
        stripped = stripped.strip()
        if not stripped:
            continue

        # Match layer header
        m = re.match(r'LAYER\s+(\d+):\s+(.*)', stripped)
        if m:
            if current:
                layers.append(current)
            current = {
                'number': m.group(1),
                'name': m.group(2).strip(),
                'pattern': '',
                'desc_lines': [],
                'read_time': '',
            }
            continue

        if current is None:
            continue

        # Match pattern line
        pm = re.match(r'Pattern:\s+(.*)', stripped)
        if pm:
            current['pattern'] = pm.group(1).strip()
            continue

        # Match read time
        rm = re.match(r'Read time:\s+(.*)', stripped)
        if rm:
            current['read_time'] = rm.group(1).strip()
            continue

        # Otherwise it's a description line
        if stripped and stripped != '│':
            current['desc_lines'].append(stripped)

    if current:
        layers.append(current)

    return layers if layers else None


def build_layer_cards(layers, styles, brand):
    """Build a branded stacked-card table for architecture layers."""
    avail = letter[0] - 2 * PAGE_MARGIN

    elements = []
    for idx, layer in enumerate(layers):
        # Alternate background: primary_light and white
        bg = brand["primary_light"] if idx % 2 == 0 else colors.white

        # Build description text
        desc = ' '.join(layer['desc_lines'])

        # Number cell (narrow left column)
        num_para = Paragraph(layer['number'], styles['Brief_LayerNumber'])

        # Content cell: name, pattern, description
        name_para = Paragraph(layer['name'], styles['Brief_LayerName'])
        pattern_para = Paragraph(layer['pattern'], styles['Brief_LayerPattern'])
        desc_para = Paragraph(desc, styles['Brief_LayerDesc']) if desc else Spacer(1, 1)

        # Stack name + pattern + desc using a nested table
        inner_data = [[name_para], [pattern_para]]
        if desc:
            inner_data.append([desc_para])
        inner = Table(inner_data, colWidths=[avail - 1.1 * inch])
        inner.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ]))

        # Read time cell (right column)
        time_para = Paragraph(layer['read_time'], styles['Brief_LayerTime'])

        row_data = [[num_para, inner, time_para]]
        row_table = Table(row_data, colWidths=[0.45 * inch, avail - 1.45 * inch, 1.0 * inch])

        style_cmds = [
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BACKGROUND', (0, 0), (-1, -1), bg),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (0, -1), 8),
            ('RIGHTPADDING', (-1, 0), (-1, -1), 8),
        ]

        # Left accent bar via a thin colored column border
        if idx == 0:
            # Top row gets top border
            style_cmds.append(('LINEABOVE', (0, 0), (-1, 0), 1, brand["primary"]))
        style_cmds.append(('LINEBELOW', (0, 0), (-1, 0), 0.5, brand["border"]))
        style_cmds.append(('LINEBEFORE', (0, 0), (0, -1), 3, brand["primary"]))

        if idx == len(layers) - 1:
            # Bottom row gets bottom border
            style_cmds.append(('LINEBELOW', (0, 0), (-1, 0), 1, brand["primary"]))

        row_table.setStyle(TableStyle(style_cmds))
        elements.append(row_table)

    return elements


def parse_markdown(md_text):
    """Parse markdown into block tokens."""
    blocks = []
    lines = md_text.split('\n')
    i = 0

    while i < len(lines):
        line = lines[i]

        if not line.strip():
            i += 1
            continue

        if re.match(r'^---+\s*$', line):
            blocks.append({'type': 'hr'})
            i += 1
            continue

        m = re.match(r'^(#{1,4})\s+(.*)', line)
        if m:
            blocks.append({'type': f'h{len(m.group(1))}', 'text': m.group(2).strip()})
            i += 1
            continue

        if re.match(r'^>\s+', line):
            quote_lines = []
            while i < len(lines) and (lines[i].startswith('>') or (lines[i].strip() and quote_lines)):
                quote_lines.append(re.sub(r'^>\s*', '', lines[i]))
                i += 1
            blocks.append({'type': 'blockquote', 'text': ' '.join(quote_lines)})
            continue

        if '|' in line and line.strip().startswith('|'):
            table_lines = []
            while i < len(lines) and '|' in lines[i] and lines[i].strip().startswith('|'):
                table_lines.append(lines[i])
                i += 1
            blocks.append({'type': 'table', 'lines': table_lines})
            continue

        if line.strip().startswith('```'):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('```'):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            blocks.append({'type': 'code', 'text': '\n'.join(code_lines)})
            continue

        m = re.match(r'^(\s*)[-*]\s+(.*)', line)
        if m:
            items = []
            while i < len(lines) and re.match(r'^(\s*)[-*]\s+(.*)', lines[i]):
                bm = re.match(r'^(\s*)[-*]\s+(.*)', lines[i])
                items.append(bm.group(2).strip())
                i += 1
            blocks.append({'type': 'bullets', 'items': items})
            continue

        m = re.match(r'^(\s*)\d+\.\s+(.*)', line)
        if m:
            items = []
            while i < len(lines) and re.match(r'^(\s*)\d+\.\s+(.*)', lines[i]):
                nm = re.match(r'^(\s*)\d+\.\s+(.*)', lines[i])
                items.append(nm.group(2).strip())
                i += 1
            blocks.append({'type': 'numbered', 'items': items})
            continue

        para_lines = []
        while i < len(lines) and lines[i].strip() and not lines[i].startswith('#') \
                and not lines[i].startswith('|') and not re.match(r'^---', lines[i]) \
                and not re.match(r'^[-*]\s+', lines[i]) and not re.match(r'^\d+\.\s+', lines[i]) \
                and not lines[i].startswith('>') and not lines[i].strip().startswith('```'):
            para_lines.append(lines[i])
            i += 1
        if para_lines:
            text = ' '.join(para_lines)
            # Detect verdict lines
            if text.startswith('**Verdict:**'):
                blocks.append({'type': 'verdict', 'text': text})
            else:
                blocks.append({'type': 'paragraph', 'text': text})

    return blocks


def parse_table(table_lines):
    rows = []
    for line in table_lines:
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        rows.append(cells)
    if len(rows) < 2:
        return rows, False
    sep = rows[1]
    if all(re.match(r'^[-:]+$', c.strip()) for c in sep if c.strip()):
        return [rows[0]] + rows[2:], True
    return rows, False


def build_pdf_table(table_lines, styles, brand):
    rows, has_header = parse_table(table_lines)
    if not rows:
        return None

    num_cols = max(len(r) for r in rows)
    rows = [r + [''] * (num_cols - len(r)) for r in rows]

    brand_hex = brand["primary"].hexval() if hasattr(brand["primary"], 'hexval') else "#37474F"

    data = []
    for ri, row in enumerate(rows):
        pdf_row = []
        for cell in row:
            style = styles['Brief_TableHeader'] if (ri == 0 and has_header) else styles['Brief_TableCell']
            pdf_row.append(Paragraph(inline_markup(cell, brand_hex), style))
        data.append(pdf_row)

    avail = letter[0] - 2 * PAGE_MARGIN
    col_width = avail / num_cols

    t = Table(data, colWidths=[col_width] * num_cols)

    style_cmds = [
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, brand["border"]),
    ]

    if has_header:
        style_cmds += [
            ('BACKGROUND', (0, 0), (-1, 0), brand["primary"]),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ]

    for ri in range(1 if has_header else 0, len(data)):
        if ri % 2 == 0:
            style_cmds.append(('BACKGROUND', (0, ri), (-1, ri), brand["primary_light"]))

    t.setStyle(TableStyle(style_cmds))
    return t


def header_footer(canvas, doc, brand, logo_path=None):
    canvas.saveState()
    width, height = letter

    canvas.setStrokeColor(brand["primary"])
    canvas.setLineWidth(2)
    canvas.line(PAGE_MARGIN, height - 0.5 * inch, width - PAGE_MARGIN, height - 0.5 * inch)

    if logo_path and os.path.exists(logo_path):
        try:
            canvas.drawImage(logo_path, PAGE_MARGIN, height - 0.48 * inch,
                             width=1.2 * inch, height=0.35 * inch,
                             preserveAspectRatio=True, mask='auto')
        except Exception:
            pass
    else:
        canvas.setFont('Helvetica-Bold', 9)
        canvas.setFillColor(brand["primary"])
        canvas.drawString(PAGE_MARGIN, height - 0.42 * inch, brand["name"])

    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(brand["text_secondary"])
    canvas.drawString(PAGE_MARGIN, 0.4 * inch, brand["footer"])
    canvas.drawRightString(width - PAGE_MARGIN, 0.4 * inch, f'Page {doc.page}')

    canvas.setStrokeColor(brand["border"])
    canvas.setLineWidth(0.5)
    canvas.line(PAGE_MARGIN, 0.55 * inch, width - PAGE_MARGIN, 0.55 * inch)

    canvas.restoreState()


def _render_bullet_with_hierarchy(item, styles, brand_hex):
    """Render a bullet with visual hierarchy: bold title in brand color, body in normal text."""
    # Detect pattern: **bold title** — rest of text
    m = re.match(r'^(\*\*[^*]+\*\*)\s*[—–-]\s*(.*)', item)
    if m:
        title_md = m.group(1)
        body = m.group(2)
        # Convert the bold title to brand-colored bold
        title_markup = inline_markup(title_md, brand_hex)
        title_markup = title_markup.replace('<b>', f'<b><font color="{brand_hex}">')
        title_markup = title_markup.replace('</b>', '</font></b>')
        body_markup = inline_markup(body, brand_hex)
        return f'<bullet>&bull;</bullet> {title_markup} — {body_markup}'
    else:
        return f'<bullet>&bull;</bullet> {inline_markup(item, brand_hex)}'


def render_brief(md_path, brand, logo_path=None, output_path=None):
    if not os.path.exists(md_path):
        print(f"Error: {md_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(md_path, 'r') as f:
        md_text = f.read()

    if not output_path:
        output_path = os.path.splitext(md_path)[0] + '.pdf'

    styles = build_styles(brand)
    blocks = parse_markdown(md_text)
    brand_hex = brand["primary"].hexval() if hasattr(brand["primary"], 'hexval') else "#37474F"

    story = []
    story.append(Spacer(1, 0.3 * inch))

    # Track section groups for KeepTogether
    i = 0
    while i < len(blocks):
        block = blocks[i]
        btype = block['type']

        if btype == 'h1':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Title']))
            story.append(Spacer(1, 2))
            i += 1

        elif btype == 'h2':
            # Conditional page break: ensure at least 2 inches remain
            story.append(CondPageBreak(MIN_H2_SPACE))

            # Collect H2 + following content into a KeepTogether group
            # (header + rule + first child element)
            h2_group = [
                HRFlowable(width='100%', thickness=1, color=brand["primary"],
                            spaceAfter=2, spaceBefore=2),
                Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_H2']),
            ]

            # Peek ahead: keep the first content block with the heading
            if i + 1 < len(blocks) and blocks[i + 1]['type'] not in ('h2', 'hr'):
                # We'll just use KeepTogether for the heading + rule
                pass

            story.append(KeepTogether(h2_group))
            i += 1

        elif btype == 'h3':
            # Keep H3 with its first content block
            h3_group = [
                Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_H3']),
            ]
            story.append(KeepTogether(h3_group))
            i += 1

        elif btype == 'hr':
            story.append(Spacer(1, 2))
            story.append(HRFlowable(width='100%', thickness=0.5, color=brand["border"],
                                    spaceAfter=2, spaceBefore=2))
            i += 1

        elif btype == 'verdict':
            # KeepTogether for verdict + evidence line
            verdict_group = [
                Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Verdict']),
            ]
            # Look ahead for evidence line
            if i + 1 < len(blocks) and blocks[i + 1]['type'] == 'paragraph':
                next_text = blocks[i + 1].get('text', '')
                if 'Evidence:' in next_text or 'evidence' in next_text.lower():
                    verdict_group.append(Spacer(1, 2))
                    verdict_group.append(
                        Paragraph(inline_markup(next_text, brand_hex), styles['Brief_Body'])
                    )
                    i += 1  # skip the evidence line since we consumed it
            story.append(KeepTogether(verdict_group))
            i += 1

        elif btype == 'blockquote':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Verdict']))
            i += 1

        elif btype == 'paragraph':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Body']))
            i += 1

        elif btype == 'bullets':
            bullet_elements = []
            for item in block['items']:
                markup = _render_bullet_with_hierarchy(item, styles, brand_hex)
                bullet_elements.append(
                    Paragraph(markup, styles['Brief_Bullet'])
                )
            story.extend(bullet_elements)
            i += 1

        elif btype == 'numbered':
            for idx, item in enumerate(block['items'], 1):
                story.append(Paragraph(
                    f'<bullet>{idx}.</bullet> {inline_markup(item, brand_hex)}',
                    styles['Brief_Bullet']
                ))
            i += 1

        elif btype == 'code':
            code_text = block['text']

            # Detect box-drawing diagrams and render as branded layer cards
            if _has_box_drawing(code_text):
                layers = _parse_layer_diagram(code_text)
                if layers:
                    cards = build_layer_cards(layers, styles, brand)
                    # Wrap all cards in KeepTogether if they fit
                    story.append(KeepTogether(cards))
                    i += 1
                    continue

            # Regular code block — monospace with background
            code_text = code_text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            code_text = code_text.replace('\n', '<br/>')
            story.append(Paragraph(code_text, styles['Brief_Code']))
            i += 1

        elif btype == 'table':
            t = build_pdf_table(block['lines'], styles, brand)
            if t:
                story.append(Spacer(1, 2))
                story.append(KeepTogether([t]))
                story.append(Spacer(1, 4))
            i += 1

        else:
            i += 1

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch
    )

    def on_page(canvas, doc):
        header_footer(canvas, doc, brand, logo_path)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    print(f"PDF saved: {output_path}")
    return output_path


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Render research brief to branded PDF')
    parser.add_argument('brief_path', help='Path to BRIEF.md')
    parser.add_argument('--brand', choices=list(BRANDS.keys()), default='research',
                        help='Brand preset (default: research)')
    parser.add_argument('--brand-color', help='Override primary brand color (hex)')
    parser.add_argument('--brand-name', help='Override brand name')
    parser.add_argument('--logo', help='Path to logo PNG')
    parser.add_argument('--output', '-o', help='Output PDF path')
    args = parser.parse_args()

    brand = get_brand(args)
    render_brief(args.brief_path, brand, logo_path=args.logo, output_path=args.output)
