#!/usr/bin/env python3
"""
render-brief.py — Convert a research BRIEF.md to a branded PDF.

Standalone renderer for research.md. No shared code with other pipelines.
Learns from render_adr.py patterns but is independently maintained.

Usage:
    python3 render-brief.py BRIEF.md
    python3 render-brief.py BRIEF.md --brand connection-forge
    python3 render-brief.py BRIEF.md --brand-color "#193B2D" --brand-name "AIC Holdings"
    python3 render-brief.py BRIEF.md --logo logo.png -o output.pdf

Brand presets:
    --brand connection-forge   → AIC green, "Connection Forge" footer
    --brand aic                → AIC blue, "AIC Holdings" footer
    --brand research           → Neutral gray, "research.md" footer
"""

import argparse
import os
import re
import sys

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
        HRFlowable, KeepTogether
    )
    from reportlab.lib.enums import TA_LEFT
except ImportError:
    print("pip install reportlab", file=sys.stderr)
    sys.exit(1)


# ── Brand Presets ─────────────────────────────────────────────────────────────

BRANDS = {
    "connection-forge": {
        "primary": "#193B2D",
        "primary_light": "#E8F5E9",
        "primary_med": "#A5D6A7",
        "name": "Connection Forge",
        "footer": "Connection Forge — Vendor Integration Contracts by AIC Holdings",
    },
    "aic": {
        "primary": "#1B365D",
        "primary_light": "#E3F2FD",
        "primary_med": "#90CAF9",
        "name": "AIC Holdings",
        "footer": "AIC Holdings — Technology Leadership",
    },
    "research": {
        "primary": "#37474F",
        "primary_light": "#ECEFF1",
        "primary_med": "#B0BEC5",
        "name": "research.md",
        "footer": "Generated by research.md — Structured Research for AI-Augmented Decision Making",
    },
}

PAGE_MARGIN = 0.75 * inch


def get_brand(args):
    """Resolve brand settings from args."""
    if args.brand and args.brand in BRANDS:
        b = BRANDS[args.brand]
    else:
        b = BRANDS["research"]

    # Allow overrides
    if args.brand_color:
        b["primary"] = args.brand_color
    if args.brand_name:
        b["name"] = args.brand_name
        b["footer"] = args.brand_name

    return {
        "primary": colors.HexColor(b["primary"]),
        "primary_light": colors.HexColor(b["primary_light"]),
        "primary_med": colors.HexColor(b["primary_med"]),
        "name": b["name"],
        "footer": b["footer"],
        "text": colors.HexColor("#1a1a1a"),
        "text_secondary": colors.HexColor("#4a4a4a"),
        "border": colors.HexColor(b.get("primary_med", "#B0BEC5")),
    }


def build_styles(brand):
    """Create branded paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        'Brief_Title', parent=styles['Title'],
        fontSize=22, leading=28, textColor=brand["primary"],
        spaceAfter=4, fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        'Brief_Subtitle', parent=styles['Normal'],
        fontSize=12, leading=16, textColor=brand["text_secondary"],
        spaceAfter=12, fontName='Helvetica-Oblique'
    ))
    styles.add(ParagraphStyle(
        'Brief_Meta', parent=styles['Normal'],
        fontSize=9, leading=13, textColor=brand["text_secondary"],
        spaceAfter=2, fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        'Brief_H2', parent=styles['Heading2'],
        fontSize=14, leading=18, textColor=brand["primary"],
        spaceBefore=16, spaceAfter=6, fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        'Brief_H3', parent=styles['Heading3'],
        fontSize=11, leading=15, textColor=brand["primary"],
        spaceBefore=12, spaceAfter=4, fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        'Brief_Body', parent=styles['Normal'],
        fontSize=10, leading=14, textColor=brand["text"],
        spaceAfter=6, fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        'Brief_Verdict', parent=styles['Normal'],
        fontSize=11, leading=16, textColor=brand["text"],
        spaceAfter=8, fontName='Helvetica-Bold',
        backColor=brand["primary_light"],
        borderColor=brand["primary"], borderWidth=1, borderPadding=8,
    ))
    styles.add(ParagraphStyle(
        'Brief_Bullet', parent=styles['Normal'],
        fontSize=10, leading=14, textColor=brand["text"],
        spaceAfter=3, fontName='Helvetica',
        leftIndent=18, bulletIndent=6
    ))
    styles.add(ParagraphStyle(
        'Brief_Code', parent=styles['Code'],
        fontSize=7, leading=10, textColor=colors.HexColor('#333333'),
        backColor=colors.HexColor('#f5f5f5'),
        borderColor=brand["border"], borderWidth=0.5, borderPadding=6,
        fontName='Courier', spaceAfter=8
    ))
    styles.add(ParagraphStyle(
        'Brief_TableCell', parent=styles['Normal'],
        fontSize=9, leading=12, textColor=brand["text"],
        fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        'Brief_TableHeader', parent=styles['Normal'],
        fontSize=9, leading=12, textColor=colors.white,
        fontName='Helvetica-Bold'
    ))
    return styles


def inline_markup(text, brand_hex="#37474F"):
    """Convert inline markdown to reportlab XML markup."""
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<b><i>\1</i></b>', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    text = re.sub(r'`([^`]+)`', rf'<font face="Courier" size="8" color="{brand_hex}">\1</font>', text)
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'<u>\1</u>', text)
    # Escape XML then restore tags
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    for tag in ['b', 'i', 'u', 'font']:
        text = text.replace(f'&lt;{tag}&gt;', f'<{tag}>')
        text = text.replace(f'&lt;{tag} ', f'<{tag} ')
        text = text.replace(f'&lt;/{tag}&gt;', f'</{tag}>')
    text = re.sub(r'<font([^&]*?)&gt;', r'<font\1>', text)
    return text


def parse_markdown(md_text):
    """Parse markdown into block tokens."""
    blocks = []
    lines = md_text.split('\n')
    i = 0

    while i < len(lines):
        line = lines[i]

        if not line.strip():
            i += 1
            continue

        if re.match(r'^---+\s*$', line):
            blocks.append({'type': 'hr'})
            i += 1
            continue

        m = re.match(r'^(#{1,4})\s+(.*)', line)
        if m:
            blocks.append({'type': f'h{len(m.group(1))}', 'text': m.group(2).strip()})
            i += 1
            continue

        if re.match(r'^>\s+', line):
            quote_lines = []
            while i < len(lines) and (lines[i].startswith('>') or (lines[i].strip() and quote_lines)):
                quote_lines.append(re.sub(r'^>\s*', '', lines[i]))
                i += 1
            blocks.append({'type': 'blockquote', 'text': ' '.join(quote_lines)})
            continue

        if '|' in line and line.strip().startswith('|'):
            table_lines = []
            while i < len(lines) and '|' in lines[i] and lines[i].strip().startswith('|'):
                table_lines.append(lines[i])
                i += 1
            blocks.append({'type': 'table', 'lines': table_lines})
            continue

        if line.strip().startswith('```'):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('```'):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            blocks.append({'type': 'code', 'text': '\n'.join(code_lines)})
            continue

        m = re.match(r'^(\s*)[-*]\s+(.*)', line)
        if m:
            items = []
            while i < len(lines) and re.match(r'^(\s*)[-*]\s+(.*)', lines[i]):
                bm = re.match(r'^(\s*)[-*]\s+(.*)', lines[i])
                items.append(bm.group(2).strip())
                i += 1
            blocks.append({'type': 'bullets', 'items': items})
            continue

        m = re.match(r'^(\s*)\d+\.\s+(.*)', line)
        if m:
            items = []
            while i < len(lines) and re.match(r'^(\s*)\d+\.\s+(.*)', lines[i]):
                nm = re.match(r'^(\s*)\d+\.\s+(.*)', lines[i])
                items.append(nm.group(2).strip())
                i += 1
            blocks.append({'type': 'numbered', 'items': items})
            continue

        para_lines = []
        while i < len(lines) and lines[i].strip() and not lines[i].startswith('#') \
                and not lines[i].startswith('|') and not re.match(r'^---', lines[i]) \
                and not re.match(r'^[-*]\s+', lines[i]) and not re.match(r'^\d+\.\s+', lines[i]) \
                and not lines[i].startswith('>') and not lines[i].strip().startswith('```'):
            para_lines.append(lines[i])
            i += 1
        if para_lines:
            text = ' '.join(para_lines)
            # Detect verdict lines
            if text.startswith('**Verdict:**'):
                blocks.append({'type': 'verdict', 'text': text})
            else:
                blocks.append({'type': 'paragraph', 'text': text})

    return blocks


def parse_table(table_lines):
    rows = []
    for line in table_lines:
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        rows.append(cells)
    if len(rows) < 2:
        return rows, False
    sep = rows[1]
    if all(re.match(r'^[-:]+$', c.strip()) for c in sep if c.strip()):
        return [rows[0]] + rows[2:], True
    return rows, False


def build_pdf_table(table_lines, styles, brand):
    rows, has_header = parse_table(table_lines)
    if not rows:
        return None

    num_cols = max(len(r) for r in rows)
    rows = [r + [''] * (num_cols - len(r)) for r in rows]

    brand_hex = brand["primary"].hexval() if hasattr(brand["primary"], 'hexval') else "#37474F"

    data = []
    for ri, row in enumerate(rows):
        pdf_row = []
        for cell in row:
            style = styles['Brief_TableHeader'] if (ri == 0 and has_header) else styles['Brief_TableCell']
            pdf_row.append(Paragraph(inline_markup(cell, brand_hex), style))
        data.append(pdf_row)

    avail = letter[0] - 2 * PAGE_MARGIN
    col_width = avail / num_cols

    t = Table(data, colWidths=[col_width] * num_cols)

    style_cmds = [
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, brand["border"]),
    ]

    if has_header:
        style_cmds += [
            ('BACKGROUND', (0, 0), (-1, 0), brand["primary"]),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ]

    for ri in range(1 if has_header else 0, len(data)):
        if ri % 2 == 0:
            style_cmds.append(('BACKGROUND', (0, ri), (-1, ri), brand["primary_light"]))

    t.setStyle(TableStyle(style_cmds))
    return t


def header_footer(canvas, doc, brand, logo_path=None):
    canvas.saveState()
    width, height = letter

    canvas.setStrokeColor(brand["primary"])
    canvas.setLineWidth(2)
    canvas.line(PAGE_MARGIN, height - 0.5 * inch, width - PAGE_MARGIN, height - 0.5 * inch)

    if logo_path and os.path.exists(logo_path):
        try:
            canvas.drawImage(logo_path, PAGE_MARGIN, height - 0.48 * inch,
                             width=1.2 * inch, height=0.35 * inch,
                             preserveAspectRatio=True, mask='auto')
        except Exception:
            pass
    else:
        canvas.setFont('Helvetica-Bold', 9)
        canvas.setFillColor(brand["primary"])
        canvas.drawString(PAGE_MARGIN, height - 0.42 * inch, brand["name"])

    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(brand["text_secondary"])
    canvas.drawString(PAGE_MARGIN, 0.4 * inch, brand["footer"])
    canvas.drawRightString(width - PAGE_MARGIN, 0.4 * inch, f'Page {doc.page}')

    canvas.setStrokeColor(brand["border"])
    canvas.setLineWidth(0.5)
    canvas.line(PAGE_MARGIN, 0.55 * inch, width - PAGE_MARGIN, 0.55 * inch)

    canvas.restoreState()


def render_brief(md_path, brand, logo_path=None, output_path=None):
    if not os.path.exists(md_path):
        print(f"Error: {md_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(md_path, 'r') as f:
        md_text = f.read()

    if not output_path:
        output_path = os.path.splitext(md_path)[0] + '.pdf'

    styles = build_styles(brand)
    blocks = parse_markdown(md_text)
    brand_hex = brand["primary"].hexval() if hasattr(brand["primary"], 'hexval') else "#37474F"

    story = []
    story.append(Spacer(1, 0.3 * inch))

    for block in blocks:
        btype = block['type']

        if btype == 'h1':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Title']))
            story.append(Spacer(1, 4))

        elif btype == 'h2':
            story.append(Spacer(1, 4))
            story.append(HRFlowable(width='100%', thickness=1, color=brand["primary"],
                                    spaceAfter=4, spaceBefore=8))
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_H2']))

        elif btype == 'h3':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_H3']))

        elif btype == 'hr':
            story.append(HRFlowable(width='100%', thickness=0.5, color=brand["border"],
                                    spaceAfter=8, spaceBefore=8))

        elif btype == 'verdict':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Verdict']))

        elif btype == 'blockquote':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Verdict']))

        elif btype == 'paragraph':
            story.append(Paragraph(inline_markup(block['text'], brand_hex), styles['Brief_Body']))

        elif btype == 'bullets':
            for item in block['items']:
                story.append(Paragraph(
                    f'<bullet>&bull;</bullet> {inline_markup(item, brand_hex)}',
                    styles['Brief_Bullet']
                ))

        elif btype == 'numbered':
            for idx, item in enumerate(block['items'], 1):
                story.append(Paragraph(
                    f'<bullet>{idx}.</bullet> {inline_markup(item, brand_hex)}',
                    styles['Brief_Bullet']
                ))

        elif btype == 'code':
            # Wrap long code lines
            code_text = block['text'].replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            code_text = code_text.replace('\n', '<br/>')
            story.append(Paragraph(code_text, styles['Brief_Code']))

        elif btype == 'table':
            t = build_pdf_table(block['lines'], styles, brand)
            if t:
                story.append(Spacer(1, 4))
                story.append(t)
                story.append(Spacer(1, 8))

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch
    )

    def on_page(canvas, doc):
        header_footer(canvas, doc, brand, logo_path)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    print(f"PDF saved: {output_path}")
    return output_path


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Render research brief to branded PDF')
    parser.add_argument('brief_path', help='Path to BRIEF.md')
    parser.add_argument('--brand', choices=list(BRANDS.keys()), default='research',
                        help='Brand preset (default: research)')
    parser.add_argument('--brand-color', help='Override primary brand color (hex)')
    parser.add_argument('--brand-name', help='Override brand name')
    parser.add_argument('--logo', help='Path to logo PNG')
    parser.add_argument('--output', '-o', help='Output PDF path')
    args = parser.parse_args()

    brand = get_brand(args)
    render_brief(args.brief_path, brand, logo_path=args.logo, output_path=args.output)
